[package]
name = "ob-types-base"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "*"

[target.'cfg(target_arch = "wasm32")'.dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
serde = { version = "*", features = ["derive"]}
serde_json = { version = "*"}
