[package]
name = "ob-types-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "*", features = ["full"]}
quote = "*"
proc-macro2 = "*"
ob-types-base = { path = "../ob-types-base"}
serde = { version = "*", features = ["derive"] }

[features]

[lib]
proc-macro = true
