[package]
name = "ob-types-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "*", features = ["full"]}
quote = "*"
proc-macro2 = "*"
proc-macro-error = { version = "1", default-features = false }

[features]

[lib]
proc-macro = true
