[package]
name = "ob-types-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "*", features = ["full"]}
quote = "*"
proc-macro2 = "*"

[features]
default = []
ob12 = []

[lib]
proc-macro = true
